baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "arn:aws:execute-api:us-west-1:451111272122:q4ai378rrd/*/*/student00-comments-post"