baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "https://q4ai378rrd.execute-api.us-west-1.amazonaws.com/default/student00-comments-post"